// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/android-chrome-192x192.png"
    | "/android-chrome-512x512.png"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/favicon-16x16.png"
    | "/favicon-32x32.png"
    | "/images/kaamelott/kaamelott-photo-1345687.jpg"
    | "/images/kaamelott/kaamelott-photo-1387933.jpg"
    | "/images/kaamelott/kaamelott-photo-1387934.jpg"
    | "/images/kaamelott/kaamelott-photo-1387938.jpg"
    | "/images/kaamelott/kaamelott-photo-1387942.jpg"
    | "/images/kaamelott/kaamelott-photo-1387943.jpg"
    | "/images/kaamelott/kaamelott-photo-1387952.jpg"
    | "/images/kaamelott/kaamelott-photo-1387954.jpg"
    | "/images/kaamelott/kaamelott-photo-1387964.jpg"
    | "/images/kaamelott/kaamelott-photo-1388383.jpg"
    | "/images/kaamelott/kaamelott-photo-1388385.webp"
    | "/images/kaamelott/kaamelott-photo-1388387.jpg"
    | "/images/kaamelott/kaamelott-photo-1388388.jpg"
    | "/images/kaamelott/kaamelott-photo-1388389.jpg"
    | "/images/kaamelott/kaamelott-photo-1388782.jpg"
    | "/images/kaamelott/kaamelott-photo-alexandre-astier-anne-girouard-1386945.jpg"
    | "/images/kaamelott/kaamelott-photo-geraldine-nakache-alain-chabat-1386989.jpg"
    | "/images/kaamelott/kaamelott-photo-kaamelott-1054514.jpg"
    | "/images/kaamelott/kaamelott-premier-volet-photo-jacques-chambon-1386962.jpg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
